export const GAMES_DATA = [
  {
    id: '1',
    title: 'Новогодний Караоке Эдишн',
    theme: 'Караоке Эдишн',
    dateInfo: {
      day: '19',
      month: 'февраля',
    },
    price: '500 p',
    seatsOccupied: '126',
    seats: '500',
    applications: '8',
  },
  {
    id: '2',
    title: 'Новогодний Караоке Эдишн',
    theme: 'Караоке Эдишн',
    dateInfo: {
      day: '19',
      month: 'февраля',
    },
    price: '500 p',
    seatsOccupied: '126',
    seats: '500',
    applications: '12',
  },
  {
    id: '3',
    title: 'Новогодний Караоке Эдишн',
    theme: 'Караоке Эдишн',
    dateInfo: {
      day: '19',
      month: 'февраля',
    },
    price: '500 p',
    seatsOccupied: '126',
    seats: '500',
    applications: '1',
  },
  {
    id: '4',
    title: 'Новогодний Караоке Эдишн',
    theme: 'Караоке Эдишн',
    dateInfo: {
      day: '19',
      month: 'февраля',
    },
    price: '500 p',
    seatsOccupied: '126',
    seats: '500',
    applications: '5',
  },
  {
    id: '5',
    title: 'Новогодний Караоке Эдишн',
    theme: 'Караоке Эдишн',
    dateInfo: {
      day: '19',
      month: 'февраля',
    },
    price: '500 p',
    seatsOccupied: '126',
    seats: '500',
    applications: '3',
  },
];
