export const INITIAL_GAME_DATA = {
  id: 0,
  gameName: '',
  gameType: '',
  gameDate: '',
  gameTime: '',
  gameLocationName: '',
  franchiseeId: 0,
  gameAddress: {
    city: '',
    street: '',
    building: '',
  },
  gameCityName: '',
  gameBasePrice: '',
  gameCurrencyPrice: '',
  gameCityId: 0,
  info: {
    description: '',
    imageSrc: '',
    coordinates: [],
  },
  adminInfo: {
    gameMaxPlayersCount: 0,
    playersAppliedCount: 0,
    playersConfirmedCount: 0,
    teamsAppliedCount: 0,
    teamsConfirmedCount: 0,
  },
};
