export const INITIAL_GAME_DATA = {
  id: '',
  gameName: '',
  gameType: '',
  gameDate: '',
  gameTime: '',
  gameLocationName: '',
  defaultFramchizeId: '',
  address: '',
  cityName: '',
  showToUsers: true,
  gameDescription: '',
  maxPlayersCount: '',
  priceValue: '',
  gameLocationId: '',
  applicationSheetName: '',
  franchiseeId: '',
};
