export const INITIAL_API_DATA = {
  id: 0,
  gameName: '',
  gameType: '',
  gameDate: '',
  gameTime: '',
  gameLocationName: '',
  franchiseeId: 0,
  address: '',
  gameCityName: '',
  gameBasePrice: '',
  gameCurrencyPrice: '',
  gameCityId: 0,
  info: {
    description: '',
    imageSrc: '',
    coordinates: [],
  },
  priceValue: '222',
};
